### ISSUE TITLE
Error with Timebox mini

### ISSUE THREAD

**Issue by RobinCutshaw** [ScR4tCh/timebox#18]
When running with a Timebox mini on Ubuntu 18.04.4 and python 3.6:

$ python3 timebox.py --debug --address 11:75:58:xx:xx:xx clock
connecting to 11:75:58:xx:xx:xx
-> ['01', '04', '00', '45', '00', '49', '00', '02']
Traceback (most recent call last):
  File "timebox.py", line 546, in <module>
    dev, disconnect = cli(sys.argv[1:], obj={})
  File "/home/robin/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/robin/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/robin/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/robin/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/robin/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/robin/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "timebox.py", line 206, in clock
    ctx.obj['dev'].send(switch_view("clock"))
  File "timebox.py", line 79, in send
    ret = [ord(c) for c in self.sock.recv(256)]
  File "timebox.py", line 79, in <listcomp>
    ret = [ord(c) for c in self.sock.recv(256)]
TypeError: ord() expected string of length 1, but int found

**Comment by VincentSC** [comment]
`timebox.py command options` and not `timebox.py options command`
